// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Rekciuq/go-bucket/ent/url"
)

// URLCreate is the builder for creating a Url entity.
type URLCreate struct {
	config
	mutation *URLMutation
	hooks    []Hook
}

// SetIsUsed sets the "is_used" field.
func (uc *URLCreate) SetIsUsed(b bool) *URLCreate {
	uc.mutation.SetIsUsed(b)
	return uc
}

// SetNillableIsUsed sets the "is_used" field if the given value is not nil.
func (uc *URLCreate) SetNillableIsUsed(b *bool) *URLCreate {
	if b != nil {
		uc.SetIsUsed(*b)
	}
	return uc
}

// SetIsImage sets the "is_image" field.
func (uc *URLCreate) SetIsImage(b bool) *URLCreate {
	uc.mutation.SetIsImage(b)
	return uc
}

// SetNillableIsImage sets the "is_image" field if the given value is not nil.
func (uc *URLCreate) SetNillableIsImage(b *bool) *URLCreate {
	if b != nil {
		uc.SetIsImage(*b)
	}
	return uc
}

// SetCreatedAt sets the "created_at" field.
func (uc *URLCreate) SetCreatedAt(t time.Time) *URLCreate {
	uc.mutation.SetCreatedAt(t)
	return uc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uc *URLCreate) SetNillableCreatedAt(t *time.Time) *URLCreate {
	if t != nil {
		uc.SetCreatedAt(*t)
	}
	return uc
}

// SetExpiresAt sets the "expires_at" field.
func (uc *URLCreate) SetExpiresAt(t time.Time) *URLCreate {
	uc.mutation.SetExpiresAt(t)
	return uc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (uc *URLCreate) SetNillableExpiresAt(t *time.Time) *URLCreate {
	if t != nil {
		uc.SetExpiresAt(*t)
	}
	return uc
}

// SetID sets the "id" field.
func (uc *URLCreate) SetID(s string) *URLCreate {
	uc.mutation.SetID(s)
	return uc
}

// Mutation returns the URLMutation object of the builder.
func (uc *URLCreate) Mutation() *URLMutation {
	return uc.mutation
}

// Save creates the Url in the database.
func (uc *URLCreate) Save(ctx context.Context) (*Url, error) {
	uc.defaults()
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *URLCreate) SaveX(ctx context.Context) *Url {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *URLCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *URLCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *URLCreate) defaults() {
	if _, ok := uc.mutation.IsUsed(); !ok {
		v := url.DefaultIsUsed
		uc.mutation.SetIsUsed(v)
	}
	if _, ok := uc.mutation.IsImage(); !ok {
		v := url.DefaultIsImage
		uc.mutation.SetIsImage(v)
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		v := url.DefaultCreatedAt()
		uc.mutation.SetCreatedAt(v)
	}
	if _, ok := uc.mutation.ExpiresAt(); !ok {
		v := url.DefaultExpiresAt()
		uc.mutation.SetExpiresAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *URLCreate) check() error {
	if _, ok := uc.mutation.IsUsed(); !ok {
		return &ValidationError{Name: "is_used", err: errors.New(`ent: missing required field "Url.is_used"`)}
	}
	if _, ok := uc.mutation.IsImage(); !ok {
		return &ValidationError{Name: "is_image", err: errors.New(`ent: missing required field "Url.is_image"`)}
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Url.created_at"`)}
	}
	if _, ok := uc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Url.expires_at"`)}
	}
	return nil
}

func (uc *URLCreate) sqlSave(ctx context.Context) (*Url, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Url.ID type: %T", _spec.ID.Value)
		}
	}
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *URLCreate) createSpec() (*Url, *sqlgraph.CreateSpec) {
	var (
		_node = &Url{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(url.Table, sqlgraph.NewFieldSpec(url.FieldID, field.TypeString))
	)
	if id, ok := uc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uc.mutation.IsUsed(); ok {
		_spec.SetField(url.FieldIsUsed, field.TypeBool, value)
		_node.IsUsed = value
	}
	if value, ok := uc.mutation.IsImage(); ok {
		_spec.SetField(url.FieldIsImage, field.TypeBool, value)
		_node.IsImage = value
	}
	if value, ok := uc.mutation.CreatedAt(); ok {
		_spec.SetField(url.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uc.mutation.ExpiresAt(); ok {
		_spec.SetField(url.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// URLCreateBulk is the builder for creating many Url entities in bulk.
type URLCreateBulk struct {
	config
	err      error
	builders []*URLCreate
}

// Save creates the Url entities in the database.
func (ucb *URLCreateBulk) Save(ctx context.Context) ([]*Url, error) {
	if ucb.err != nil {
		return nil, ucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*Url, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*URLMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *URLCreateBulk) SaveX(ctx context.Context) []*Url {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *URLCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *URLCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
